### ISSUE TITLE
speak.js compile error

### ISSUE THREAD

**Issue by dlhzt** [kripken/speak.js#59]
1 emscripten-1.37.5
2 emscripten-fastcomp-1.37.5 
3 emscripten-fastcomp-clang-1.37.5   already move it into emscripten-fastcomp-1.37.5/tools/clang

then
cd spreak.js/src
./emscripten.sh
.....

1 warning generated.
/home/zhangtao/git/emscripten-1.37.5/em++ -L/usr/local/lib -L/usr/local/BerkeleyDB.4.8/lib/ -o speak speak.o compiledict.o dictionary.o intonation.o readclause.o setlengths.o numbers.o synth_mbrola.o synthdata.o synthesize.o translate.o mbrowrap.o tr_languages.o voices.o wavegen.o phonemelist.o klatt.o sonic.o -lstdc++  -lpthread 
emscripten
error: Linking globals named 'wcschr': symbol multiply defined!
Traceback (most recent call last):
  File "/home/git/emscripten-1.37.5/emcc", line 13, in <module>
    emcc.run()
  File "/home/git/emscripten-1.37.5/emcc.py", line 1637, in run
    final = shared.Building.llvm_opt(final, link_opts, DEFAULT_FINAL)
  File "/home/git/emscripten-1.37.5/tools/shared.py", line 1838, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations: 

anybody help me!!!

**Comment by aldo-puga** [comment]
Hi @dlhzt,
I had the same problem, to solve this problem I changed function names of espeak source files, set emcc to doesn't create a external memory initializer file and used the emscripten-1.37.23 (available in emsdk).
I [have a fork](https://github.com/aldo-puga/speak.js) with these commits.
